### ISSUE TITLE
Windows is not built if workdir is another folder

### ISSUE THREAD

**Issue by chrisvire** [goreleaser/goreleaser-action#341]
I have a private repo (written by students at a college) where I am working on adding support for building with goreleaser-action.  They put the go source code in a `src` sub directory.  When the build is done in GitHub Actions, Windows is not built.  If I run `goreleaser release --rm-dist --snapshot` on my machine, it builds for Windows.

I have been able to reproduce this issue in an example repo (https://github.com/chrisvire/goreleaser-example).  

* In [Version 0.1](https://github.com/chrisvire/goreleaser-example/releases/tag/v0.1), the source is in the root folder and it builds Windows.
* In [Version 0.3](https://github.com/chrisvire/goreleaser-example/releases/tag/v0.3), the source was moved to the `src` folder and the `.goreleaser.yaml` has workdir set to `./src/` and no Windows build it done.
* In [Version 0.4](https://github.com/chrisvire/goreleaser-example/releases/tag/v0.4), the source was moved back to the root folder and `.goreleaser.yaml` has workdir set to `.` and Windows is built again.

The GitHub build logs for [Version 0.3](https://github.com/chrisvire/goreleaser-example/runs/6116594760?check_suite_focus=true) and [Version 0.4](https://github.com/chrisvire/goreleaser-example/runs/6116993449?check_suite_focus=true) have `--debug` added to the `goreleaser` line to help with figuring out why.

**Comment by caarlos0** [comment]
the gist seems to be this: https://github.com/chrisvire/goreleaser-example/runs/6116594760?check_suite_focus=true#step:5:19

that happens because you're effectively saying to run goreleaser from the src folder instead of the root folder, which is the folder that contains the goreleaser.yml file

https://github.com/chrisvire/goreleaser-example/blob/v0.3/.github/workflows/main.yml#L42

pretty sure you don't need this line.

in any case, does not look like a bug.
