### ISSUE TITLE
private repos

### ISSUE THREAD

**Issue by jkassis** [goreleaser/goreleaser-action#365]
How do we use goreleaser actions with private repos?

Here's an example of what I see...

```
⨯release failed after 1serror=failed to get module path: exit status 1: go: github.com/jkassis/jerrie@v0.0.0-20220709231134-b57fd5610c80: invalid version: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /home/runner/go/pkg/mod/cache/vcs/9cca0682a7f4c5aa67a47c8f7b1822313eb93812592811c699eba8db326c6462: exit status 128:
	fatal: could not read Username for 'https://github.com/': terminal prompts disabled
```

root cause seems to be "could not read Username"

**Comment by integrii** [comment]
I have a similar issue today.  I am trying to use goreleaser on github enterprise and it needs permissions to check out other private repositories that it appears not to have access to.  I seems like goreleaser needs some kind of credential support so that it can pull from private repositories (probably via SSH key authentication).

As a workaround, I vendored my project with `go mod vendor` and removed the pre-hook step that was in my goreleaser.yaml to purge any actions such as `go mod tidy` that might take authentication.

**Comment by caarlos0** [comment]
this is not goreleaser per se, nor the action, is simply that you need to setup your ci to pull private go modules

if you search for "golang private repositories" or something like that you'll find plenty of tutorials, but basically set GOPRIVATE and config git to replace https URLs for SSH ones.

that said, closing this.
